### ISSUE TITLE
Request to remove the video in Bosnian

### ISSUE THREAD

**Issue by aleksandar-todorovic** [watch-devtube/contrib#1]
Video in question: https://dev.tube/video/yDWvAYe3-T0

Why it should be removed:

First I was amazed by the fact that there's 1 video in my local language, knowing I come from a country in which the IT sector is extremely bad.

Then I've watched it, and it turned out to be a 90 sec report from one of our public broadcastors about a conference outside my country.

Looking at the channels.yml, it seems like it got there because all videos from WeAreDevelopers YouTube channel, but I really think that this video doesn't contribute anything to any developer. It's just a report about a conference outside of the country because the organizers are apparently of Bosnian origin (stated in the video).

On a final note, the channel says that the conference was "featured on Bosnian national TV", which is just wrong. It is a public broadcaster, but not the national public broadcaster (that would be BHT, not FTV). This is a public broadcaster for the [Federation of Bosnia & Herzegovina](https://en.wikipedia.org/wiki/Federation_of_Bosnia_and_Herzegovina), which covers ~50% of the territory of Bosnia & Herzegovina, other ~50% being covered by the third public broadcaster (RTRS).

**Comment by aadamovich** [comment]
Hi Aleksandr!

Thanks for your feedback. We decided to remove all videos shorter than 5 minutes since most of them are sort of advertisement or overview videos. This also affected the video you mentioned above :).

Keep using dev.tube! We would like to hear more suggestions from you!

Best regards,
Andrey
