### ISSUE TITLE
Make Tags case sensative

### ISSUE THREAD

**Issue by AlexeyBuzdin** [watch-devtube/contrib#176]
**Expected:**
- iOS
- IoT
- DI
- etc

**Actual:**
![image](https://user-images.githubusercontent.com/1146622/43863854-9eced01c-9b66-11e8-95d1-d182e12d1b4a.png)

I suggest to add a Map with some case exceptions or make tags in yml case sensative

**Comment by eduardsi** [comment]
Thanks for reporting this. Fixed, deployment in progress: 
https://github.com/watch-devtube/web/commit/58fa9ff8c9acf733205af7c8f5d5c50b76f2210a#diff-78f7ba8a6c59142934ff4f7e62cadc72

P.S. we normally use https://github.com/watch-devtube/web/issues for feature requests. 

Keep rocking!
