### ISSUE TITLE
channels/speakers/tags in single files do not scale

### ISSUE THREAD

**Issue by dolmen** [watch-devtube/contrib#26]
Using just 3 files for channels/speakers/tags will not scale when dealing with external contributions:
- it will make merging conflicts difficult
- it makes converting content from external sources (example list of URLs from a conference) a bit more difficult

Instead those 3 files could be split in 3 directories with one entry per file.

Also some tools should be available to detect invalid entries ([JSON schema](http://json-schema.org/specification.html) validation?) and duplicates.

**Comment by aadamovich** [comment]
Thanks, @dolmen! Yes, it makes sense to split data into several files. After 2 days in production those 3 files are still manageable, but it will get harder with time :-).

**Comment by eduardsi** [comment]
@aadamovich I think we can close this issue if 9 pending pull requests will auto-merge without a conflict (no conflicts = no problem). In case of conflict, let's keep in the backlog and split in dirs.

**Comment by aadamovich** [comment]
@eduardsi agree

@dolmen we decided to postpone data split. So, far it is manageable. We will reopen if the need arises.
