### ISSUE TITLE
Some Youtube channels for developers

### ISSUE THREAD

**Issue by ogun** [watch-devtube/contrib#29]
Hello,

You are doing a great job, thank you! I want to suggest you some of the dev channels, I subscribed on Youtube. Maybe you want to add those to your platform.

.NET Fringe Conference
https://www.youtube.com/channel/UCIz73jo7KPqVTssbUmiIfXg

Confreaks
https://www.youtube.com/channel/UCWnPjmqvljcafA0z2U1fwKQ

Curry On!
https://www.youtube.com/channel/UC-WICcSW1k3HsScuXxDrp0w

DEFCONConference
https://www.youtube.com/channel/UC6Om9kAkl32dWlDSNlDS9Iw

Devoxx
https://www.youtube.com/channel/UCCBVCTuk6uJrN3iFV_3vurg

EuroPython Conference
https://www.youtube.com/channel/UC98CzaYuFNAA_gOINFB0e4Q

FOSDEM
https://www.youtube.com/channel/UC9NuJImUbaSNKiwF2bdSfAw

GDC
https://www.youtube.com/channel/UC0JB7TSe49lg56u6qH8y_MQ

GOTO Conferences
https://www.youtube.com/channel/UCs_tLP3AiwYKwdUHpltJPuA

Hack In The Box Security Conference
https://www.youtube.com/channel/UC0BJVNTIEbG8CLG-xVVWJnA

NDC Conferences
https://www.youtube.com/channel/UCTdw38Cw6jcm0atBPA39a0Q

OWASP
https://www.youtube.com/channel/UCe8j61ABYDuPTdtjItD2veA

PyData
https://www.youtube.com/channel/UCOjD18EJYcsBog4IozkF_7w

USENIX
https://www.youtube.com/channel/UC4-GrpQBx6WCGwmwozP744Q

**Comment by aadamovich** [comment]
merged
