### ISSUE TITLE
Filter by date

### ISSUE THREAD

**Issue by bovas85** [watch-devtube/contrib#3]
I'm trying to filter videos by most recent, but I can't seem to do so. 

If possible I'd like to help via PR, but otherwise if you have any insights about this it'd be appreciated.

**Comment by aadamovich** [comment]
We have this feature planned. Most likely will be implemented in 2-3 weeks.

**Comment by aadamovich** [comment]
The code for the web is located here: https://github.com/watch-devtube/web

**Comment by aadamovich** [comment]
Moving this discussion to front-end project: https://github.com/watch-devtube/web/issues/1
