### ISSUE TITLE
Made few PRs, got no karma

### ISSUE THREAD

**Issue by glamcoder** [watch-devtube/contrib#315]
I made several pull requests which were approved, I see those reflected in the contributors page. But no videos/channels/speakers are attributed for me, so no karma.
Why? And what't the correct what to contribute so that karma is updated?

**Comment by aadamovich** [comment]
@glamcoder Thanks for noticing, it seems that there is a bug in our karma calculation system. We will fix it during weekend.

**Comment by aadamovich** [comment]
@glamcoder It is fixed now:
![image](https://user-images.githubusercontent.com/2787794/50055046-29b22e80-0152-11e9-9958-019a05451777.png)
