### ISSUE TITLE
Add channels from playlist

### ISSUE THREAD

**Issue by ankitprahladsoni** [watch-devtube/contrib#320]
When adding a playlist with videos from multiple channels, the bot should fetch all the channels in the playlist and add to its active channel list.

**Comment by sizovs** [comment]
Hi!

Thanks for raising this. Such changes are very hard to review: 

If a playlist consist of multiple channels, then checking all channels for dirty content would mean a lot of manual work. This is why we support only 2 types of contributions:
- a channel (when channel is not dirty)
- a playlist from a channel (used for filtering, t.i. when the channel has a dirty content)

If a playlist aggregates a content from many channels – it's always possible to contribute them separately. That might mean some manual, one-time work, though.

– Ed
