### ISSUE TITLE
Multiple recent channels are empty

### ISSUE THREAD

**Issue by andrey-yantsen** [watch-devtube/contrib#360]
Hi! I've recently added a bunch of channels in #357, but so far some of them aren't displaying any videos, saying `No videos matching your query`: [HighLoad](https://dev.tube/channel/HighLoad%20Channel), [PyCon 2019](https://dev.tube/channel/PyCon%202019), [PyCon 2018](https://dev.tube/channel/PyCon%202018), [PyCon 2017](https://dev.tube/channel/PyCon%202017) and [GopherCon Russia](https://dev.tube/channel/GopherCon%20Russia).

PyCon 2017 even not in the list, but for most of them there is a count of videos displayed near the channel name in the filter:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/629281/58475924-34ccaa00-8147-11e9-9519-9814a7e0437e.png">

Can you please check what went wrong?

FYI: real channel names on youtube are different from ones in the `channels.yml`.

**Comment by sizovs** [comment]
Hey @andrey-yantsen 

Thanks for reporting. HighLoad, Python 2019, Python 2018 and GopherCon works on my machine (Chrome 74 and Firefox 67). Can you check please?

Meanwhile, investigating Python 2017 issue.

![image](https://user-images.githubusercontent.com/2264968/58508966-11811980-819e-11e9-968d-a9906f6ec603.png)

**Comment by andrey-yantsen** [comment]
Ooopsie, found the reason: I had English language set in filters, and it wasn't detected automatically for PyCons. Ok, sorry for the panic :) Would be nice to see all the active filters in the same way the channel name is being displayed, I think.

**Comment by sizovs** [comment]
@andrey-yantsen thanks, opened the issue https://github.com/watch-devtube/web/issues/76. Meanwhile, investigating Python 2017.

**Comment by aadamovich** [comment]
It seems that our indexing bot has stuck a bit due to lack of resources. Going to give it a bit more memory and launch reindexing process tonight

**Comment by andrey-yantsen** [comment]
Awesome guys, thanks! For now I'm working on setting proper language tags for my videos :)

**Comment by aadamovich** [comment]
@andrey-yantsen Actually, there is an issue with PyCon 2017. All videos in that channel are marked by the owner as non-embeddable. That means that you can only view them on Youtube. Our indexing process does not add them to the main index because of that.

**Comment by aadamovich** [comment]
There is not much we can do about it. Closing this issue. Feel free to re-open if you have any comments.

**Comment by andrey-yantsen** [comment]
Ok, got it, thanks anyway!

**Comment by sizovs** [comment]
![image](https://user-images.githubusercontent.com/2264968/78665361-e7d96880-78ff-11ea-8f3b-23251520c17b.png)

@andrey-yantsen Thanks for raising this. Fixed in https://github.com/watch-devtube/web/commit/94e620b0471b1ae248d62798de6304f8ded429d3
