### ISSUE TITLE
Hacktoberfest 2021?

### ISSUE THREAD

**Issue by marc-bouvier** [watch-devtube/contrib#452]
Can contributions to this crowd sourcing repo be part of Hacktoberfest 2021?

https://hacktoberfest.digitalocean.com/

**Comment by o-rashad** [comment]
hey @sizovs , what happened to dev.tube it shows `site not found ?`

**Comment by sizovs** [comment]
Hu @od-c0d3r 

At the moment the project is offline. The best way to watch tech videos now is to use YouTube. DevTube 2.0 is under construction.
